# Generated by Django 3.2.7 on 2021-11-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('q_id', models.IntegerField(verbose_name='')),
                ('info', models.AutoField(primary_key=True, serialize=False)),
                ('upvote', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
