# Generated by Django 3.2.7 on 2021-11-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='info',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='questions',
            name='q_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
