# Generated by Django 3.2.7 on 2021-11-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211101_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='answers',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('info', models.TextField(max_length=300)),
                ('author', models.CharField(max_length=100)),
                ('for_q', models.IntegerField()),
            ],
        ),
    ]
